version: 0.2         
phases:
  install:
    runtime-versions:
      golang: 1.12
  pre_build:
    commands:
      - echo AWS-for-fluent-bit building
  build:
    commands:
      - make release
artifacts:
  files:
    - '**/*'
